name: Release Package to Nexus

on:
  workflow_dispatch:

jobs:
  publish-package:
    needs: publish-release
    name: Deploy Handlebars to Nexus
    runs-on: aws-bonprix-runner
    container:
      image: maven:3.8.4-openjdk-17
    env:
      MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    if: ${{ needs.publish-release.outputs.createdNewTag == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies && Build package
        run: |
          mvn clean install
          mvn versions:set -DnewVersion=${{ needs.publish-release.outputs.version }}
      - name: Publish to Sonatype Nexus
        run: |
          mvn deploy:deploy-file \
          -Durl=https://nexus.bonprix.work/repository/bonprix-maven/ \
          -DrepositoryId=nexus \
          -Dfile=target/handlebars.jar \
          -DpomFile=pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
