name: Release Package to Nexus

on:
  workflow_dispatch:

jobs:

  publish-package:
    name: Deploy Handlebars to Nexus
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.4-openjdk-17
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies && Build package
        run: |
          mvn clean install
      - name: Publish to Sonatype Nexus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn deploy
